name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# butuh write supaya bisa git push
permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: |
            deployment/requirements.txt
            requirements-dev.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r deployment/requirements.txt
          pip install -r requirements-dev.txt

      - name: Run tests
        run: pytest

  build-and-package:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Streamlit image
        run: docker build --tag streamlit-shipping:latest .

      - name: Export Docker image
        run: docker save streamlit-shipping:latest -o streamlit-shipping.tar

      - name: Upload deployable artifact
        uses: actions/upload-artifact@v4
        with:
          name: streamlit-shipping-image
          path: streamlit-shipping.tar

  deploy-to-hf:
    needs: test   # kalau mau nunggu build-and-package juga: [test, build-and-package]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Push to HuggingFace Space
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          # tambahkan remote HF (username & space name sesuaikan)
          git remote add hf https://vorddd:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/vorddd/MLOps-MidExam

          # kalau branch di HF belum ada, pull ini bakal fail -> kita ignore dengan || true
          git pull hf main || true

          # push branch main ke HF -> trigger build Docker di Space
          git push hf main --force
